"""Structured input-validation errors for operator solvers.

Design (V8 Phase 2 §5)
======================
- Each solver, when it cannot process an input, raises
  :class:`OperatorInputError` with a stable ``code`` from
  :data:`ERROR_CODES`.
- ``runner.execute_pipeline`` catches it and writes
  ``{error_code, error_phase, error, next_action_hint, error_args}``
  into the step's ``step_manifest.json``.
- No LLM ever rewrites the diagnosis: the ``code`` → message template
  + next_action_hint mapping is *hard-coded* here.  Downstream agents
  (Coder, case-study) read the structured fields, they do not parse
  free-form tracebacks.

Why a registry of codes?
------------------------
- Coder fallback can branch on ``error_code`` deterministically (e.g.
  on ``OUTCOME_NOT_BINARY`` switch to linear regression instead of
  guessing what went wrong from a Python traceback).
- The set of distinct failure shapes is *bounded* — keeping them in
  one table lets us audit what failure types the pipeline knows how
  to talk about.

中文说明
========
所有算子的"输入校验失败"统一通过 :class:`OperatorInputError` 抛出，
runner 捕获后把结构化字段写入 ``step_manifest.json``。错误码与人类
可读建议都**写死**在本文件，**不让 LLM 评判 / 改写**。
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict


@dataclass(frozen=True)
class ErrorCodeSpec:
    """Hard-coded specification of one operator failure mode."""
    code: str
    phase: str
    """One of: ``input_validation`` | ``shape_validation``
    | ``computation``.  Distinguishes "the caller mis-routed" (input/
    shape) from "the math itself blew up" (computation)."""
    template: str
    """``str.format``-style template with **named** placeholders.  All
    placeholders must be supplied at raise time via ``**fmt_args``."""
    next_action_hint: str
    """Short, **fixed** human-readable suggestion.  Read by Coder
    fallback and case-study tooling; never generated by an LLM."""


# ---------------------------------------------------------------------------
# Registry — keep alphabetic for easy diffing.
# ---------------------------------------------------------------------------
ERROR_CODES: Dict[str, ErrorCodeSpec] = {
    "COLUMN_NOT_FOUND": ErrorCodeSpec(
        code="COLUMN_NOT_FOUND",
        phase="input_validation",
        template=(
            "Solver {solver} expected column {col!r} but it is not in the "
            "input dataframe.  Available (first 20): {available}."
        ),
        next_action_hint=(
            "verify the mapping or the upstream csv schema; coder "
            "fallback should use the actual column names listed in "
            "operator_context."
        ),
    ),
    "COLUMN_NOT_NUMERIC": ErrorCodeSpec(
        code="COLUMN_NOT_NUMERIC",
        phase="input_validation",
        template=(
            "Solver {solver} requires a numeric column for role {col!r}; "
            "observed dtype={observed_dtype}."
        ),
        next_action_hint=(
            "either pre-cast the column to numeric upstream, or compute "
            "the statistic via __coder__."
        ),
    ),
    "OUTCOME_NOT_BINARY": ErrorCodeSpec(
        code="OUTCOME_NOT_BINARY",
        phase="input_validation",
        template=(
            "Solver {solver} requires a binary 0/1 outcome but column "
            "{col!r} has {n_unique} unique values (range [{vmin}, {vmax}])."
        ),
        next_action_hint=(
            "for a continuous outcome use linear_regression or column_stat; "
            "do not binarise the outcome silently."
        ),
    ),
    "INPUT_IS_SUMMARY_TABLE": ErrorCodeSpec(
        code="INPUT_IS_SUMMARY_TABLE",
        phase="shape_validation",
        template=(
            "Solver {solver} received what looks like a summary table "
            "(stat-name columns detected: {stat_cols}) instead of "
            "row-level data.  Computing statistics-of-statistics is "
            "almost always wrong."
        ),
        next_action_hint=(
            "feed the upstream RAW csv (e.g. __initial__) into this solver, "
            "not the output of describe_full / missing_summary / etc."
        ),
    ),
    "INPUT_IS_CONTINGENCY_TABLE": ErrorCodeSpec(
        code="INPUT_IS_CONTINGENCY_TABLE",
        phase="shape_validation",
        template=(
            "Solver {solver} received a contingency / aggregated cell "
            "table (evidence: {evidence}).  It expects patient-level rows."
        ),
        next_action_hint=(
            "compute the estimand directly from the cells via __coder__ "
            "(e.g. risk difference = a/(a+b) - c/(c+d))."
        ),
    ),
    "SUBSET_QUERY_INVALID": ErrorCodeSpec(
        code="SUBSET_QUERY_INVALID",
        phase="input_validation",
        template=(
            "Solver {solver} could not apply subset_query {query!r}: "
            "{reason}."
        ),
        next_action_hint=(
            "check pandas query syntax and column names; names containing "
            "spaces or punctuation must be wrapped in backticks."
        ),
    ),
    "NO_NUMERIC_COLUMNS": ErrorCodeSpec(
        code="NO_NUMERIC_COLUMNS",
        phase="input_validation",
        template=(
            "Solver {solver} found no usable numeric columns after "
            "filtering non-numeric/all-NaN columns."
        ),
        next_action_hint=(
            "verify mapping; if columns contain thousand-separator commas, "
            "percent signs, currency symbols or stray whitespace they are "
            "auto-coerced — but a column where <70% of cells coerce to "
            "numeric is rejected.  For such columns clean them in a "
            "__coder__ step (strip units / convert to float) before this "
            "solver."
        ),
    ),
    "INSUFFICIENT_SAMPLES": ErrorCodeSpec(
        code="INSUFFICIENT_SAMPLES",
        phase="shape_validation",
        template=(
            "Solver {solver} requires at least {required_n} valid rows "
            "(after dropna) but only {actual_n} were available."
        ),
        next_action_hint=(
            "If the data is in wide format (years / conditions as separate "
            "columns), consider melt→long format first in a __coder__ "
            "step; otherwise switch to a method that tolerates small N."
        ),
    ),
    "COLUMN_NOT_COERCIBLE": ErrorCodeSpec(
        code="COLUMN_NOT_COERCIBLE",
        phase="input_validation",
        template=(
            "Solver {solver} requires numeric column {col!r} but it is "
            "dtype={dtype} and only {coerce_rate} of values could be "
            "coerced to numeric (after stripping commas / % / currency "
            "symbols / whitespace)."
        ),
        next_action_hint=(
            "Manually clean the column with pandas (strip units / convert "
            "to float) in a __coder__ step before this solver."
        ),
    ),
    "NO_TARGET_COLUMNS": ErrorCodeSpec(
        code="NO_TARGET_COLUMNS",
        phase="input_validation",
        template=(
            "Solver {solver}: none of the requested columns ({requested}) "
            "exist or are usable in the input dataframe."
        ),
        next_action_hint=(
            "verify mapping; the upstream csv may have different column "
            "names than the planner assumed."
        ),
    ),
    "INVALID_STAT": ErrorCodeSpec(
        code="INVALID_STAT",
        phase="input_validation",
        template=(
            "Solver {solver} got stat={stat!r}, not in whitelist "
            "{whitelist}."
        ),
        next_action_hint=(
            "pick a whitelisted stat; for arbitrary statistics use "
            "__coder__."
        ),
    ),
    "WEIGHT_COL_INVALID": ErrorCodeSpec(
        code="WEIGHT_COL_INVALID",
        phase="input_validation",
        template=(
            "Solver {solver}: weight_col {col!r} is missing from the "
            "dataframe or is not numeric (observed dtype={observed_dtype})."
        ),
        next_action_hint=(
            "drop weight_col or pick a valid numeric weight column."
        ),
    ),
    "MISSING_STAT_PARAM": ErrorCodeSpec(
        code="MISSING_STAT_PARAM",
        phase="input_validation",
        template=(
            "Solver {solver} stat={stat!r} requires parameter {param!r} "
            "but it was not provided."
        ),
        next_action_hint=(
            "supply the required static_param; e.g. proportion_in_range "
            "needs value_min and/or value_max; top_k_value needs k."
        ),
    ),
    "MISSING_REQUIRED_COLUMNS": ErrorCodeSpec(
        code="MISSING_REQUIRED_COLUMNS",
        phase="input_validation",
        template=(
            "Solver {solver}: one or more required role columns / params "
            "are missing from the mapping. {hint}"
        ),
        next_action_hint=(
            "verify the planner mapped every required role (see contract "
            "roles list); for new domain solvers (cheminformatics / "
            "biosignal / single_cell) the data file path may need to be "
            "passed via the mapping (e.g. input_file / input_h5ad)."
        ),
    ),
    "INSUFFICIENT_FEATURES": ErrorCodeSpec(
        code="INSUFFICIENT_FEATURES",
        phase="input_validation",
        template=(
            "Solver {solver}: not enough usable feature columns. {hint}"
        ),
        next_action_hint=(
            "ensure feature_columns lists >= 2 columns that exist in the "
            "input csv; if many columns are non-numeric, first run "
            "encode_categorical or drop them."
        ),
    ),
    "UNSUPPORTED_FILE_FORMAT": ErrorCodeSpec(
        code="UNSUPPORTED_FILE_FORMAT",
        phase="input_validation",
        template=(
            "Solver {solver} received a file in an unsupported format. {hint}"
        ),
        next_action_hint=(
            "single-cell solvers accept .h5ad or .csv (genes × cells); "
            "convert with anndata.AnnData(...).write_h5ad(...) in a "
            "__coder__ step if needed."
        ),
    ),
    "INVALID_PARAM": ErrorCodeSpec(
        code="INVALID_PARAM",
        phase="input_validation",
        template=(
            "Solver {solver} received an invalid parameter value. {hint}"
        ),
        next_action_hint=(
            "pick a whitelisted value for the parameter; see contract "
            "static_params / description for allowed choices."
        ),
    ),
    "MISSING_DEPENDENCY": ErrorCodeSpec(
        code="MISSING_DEPENDENCY",
        phase="computation",
        template=(
            "Solver {solver} needs an optional dependency that is not "
            "installed. {hint}"
        ),
        next_action_hint=(
            "either install the dependency, or route this step to __coder__, "
            "or supply an alternative input (e.g. precomputed feature_columns "
            "instead of a smiles_col when rdkit is missing)."
        ),
    ),
}


class OperatorInputError(Exception):
    """Structured exception raised by solvers on bad input.

    Use :meth:`to_manifest` to get a dict suitable for merging into a
    ``step_manifest.json`` record.  The runner does that automatically;
    callers should not catch this themselves (unless they explicitly
    want to convert it into a friendlier UX message).

    中文：算子输入校验失败专用异常；runner 捕获后自动写结构化错误到
    ``step_manifest.json``。错误信息（``str(e)``）由 :data:`ERROR_CODES`
    里的模板**写死**生成，不依赖 LLM 总结。
    """

    _OPTIONAL_DEFAULTS = {"hint": ""}

    def __init__(self, code: str, **fmt_args: Any) -> None:
        if code not in ERROR_CODES:
            raise KeyError(
                f"unknown OperatorInputError code: {code!r}. "
                f"Add it to operator_pipeline.error_codes.ERROR_CODES."
            )
        spec = ERROR_CODES[code]
        merged = dict(self._OPTIONAL_DEFAULTS)
        merged.update(fmt_args)
        try:
            message = spec.template.format(**merged)
        except KeyError as missing:
            raise KeyError(
                f"OperatorInputError({code}): template missing placeholder "
                f"{missing}; supplied={list(fmt_args)}"
            ) from None
        super().__init__(message)
        self.code = code
        self.fmt_args: Dict[str, Any] = dict(fmt_args)
        self.spec = spec

    def to_manifest(self) -> Dict[str, Any]:
        """Return a dict to merge into a step manifest record."""
        return {
            "error_code": self.code,
            "error_phase": self.spec.phase,
            "error": str(self),
            "next_action_hint": self.spec.next_action_hint,
            "error_args": dict(self.fmt_args),
        }


__all__ = ["ERROR_CODES", "ErrorCodeSpec", "OperatorInputError"]
