# backend/clinical_evidence.py
# 2.1.6 clinical methodology evidence registry.

from __future__ import annotations

from typing import Dict, Iterable, List, Optional


EVIDENCE_REGISTRY: Dict[str, dict] = {
    "strobe_2007": {
        "id": "strobe_2007",
        "module": "patient_query",
        "method": "observational_cohort_reporting",
        "title": "The Strengthening the Reporting of Observational Studies in Epidemiology (STROBE) statement",
        "authors": "von Elm E, Altman DG, Egger M, Pocock SJ, Gotzsche PC, Vandenbroucke JP; STROBE Initiative",
        "venue": "Lancet",
        "year": 2007,
        "doi": "10.1016/S0140-6736(07)61602-X",
        "pmid": "18064739",
        "url": "https://pubmed.ncbi.nlm.nih.gov/18064739/",
        "supports": "观察性队列研究应清晰报告纳入/排除标准、数据来源、变量定义和样本选择过程。",
        "caveat": "检索结果是基于现有数据字段的队列定义，不等同于诊断确认或因果推断。",
    },
    "record_2015": {
        "id": "record_2015",
        "module": "patient_query",
        "method": "routinely_collected_health_data",
        "title": "The RECORD statement",
        "authors": "Benchimol EI et al.",
        "venue": "PLoS Medicine",
        "year": 2015,
        "doi": "10.1371/journal.pmed.1001885",
        "pmid": "26440803",
        "url": "https://pubmed.ncbi.nlm.nih.gov/26440803/",
        "supports": "常规采集医疗数据研究需报告编码、清洗、链接、可重复查询逻辑和数据质量限制。",
        "caveat": "电子病历/运营库字段可能存在缺失和测量偏差，导出结果需保留查询条件和时间戳以便复核。",
    },
    "ohdsi_cohort_2021": {
        "id": "ohdsi_cohort_2021",
        "module": "patient_query",
        "method": "computable_phenotype",
        "title": "The Book of OHDSI: Defining Cohorts",
        "authors": "OHDSI community",
        "venue": "OHDSI",
        "year": 2021,
        "doi": None,
        "pmid": None,
        "url": "https://ohdsi.github.io/TheBookOfOhdsi/Cohorts.html",
        "supports": "可计算队列应由纳入条件、排除条件和时间逻辑定义，并可复现。",
        "caveat": "本系统提供可计算筛选和批量导出，真实研究仍需做源记录核查和表型有效性评估。",
    },
    "hamd_1960": {
        "id": "hamd_1960",
        "module": "reference_range",
        "method": "HAMD_total",
        "title": "A rating scale for depression",
        "authors": "Hamilton M",
        "venue": "Journal of Neurology, Neurosurgery, and Psychiatry",
        "year": 1960,
        "doi": None,
        "pmid": "14399272",
        "url": "https://pubmed.ncbi.nlm.nih.gov/14399272/",
        "supports": "HAMD 可用于已诊断抑郁患者抑郁症状严重度和变化评估。",
        "caveat": "HAMD 是严重度量表，不应单独作为精神障碍诊断依据。",
    },
    "hama_1959": {
        "id": "hama_1959",
        "module": "reference_range",
        "method": "HAMA_total",
        "title": "The assessment of anxiety states by rating",
        "authors": "Hamilton M",
        "venue": "British Journal of Medical Psychology",
        "year": 1959,
        "doi": "10.1111/j.2044-8341.1959.tb00467.x",
        "pmid": "13638508",
        "url": "https://pubmed.ncbi.nlm.nih.gov/13638508/",
        "supports": "HAMA 支持焦虑症状严重度的临床评分。",
        "caveat": "HAMA 受躯体症状和共病影响，异常提示需结合临床访谈。",
    },
    "phq9_2001": {
        "id": "phq9_2001",
        "module": "reference_range",
        "method": "PHQ9_total",
        "title": "The PHQ-9: validity of a brief depression severity measure",
        "authors": "Kroenke K, Spitzer RL, Williams JBW",
        "venue": "Journal of General Internal Medicine",
        "year": 2001,
        "doi": "10.1046/j.1525-1497.2001.016009606.x",
        "pmid": "11556941",
        "url": "https://pubmed.ncbi.nlm.nih.gov/11556941/",
        "supports": "PHQ-9 是抑郁症状筛查和严重度评估的简短工具。",
        "caveat": "PHQ-9 是筛查/量化工具，阳性结果需要临床诊断确认。",
    },
    "gad7_2006": {
        "id": "gad7_2006",
        "module": "reference_range",
        "method": "GAD7_total",
        "title": "A brief measure for assessing generalized anxiety disorder: the GAD-7",
        "authors": "Spitzer RL, Kroenke K, Williams JBW, Lowe B",
        "venue": "Archives of Internal Medicine",
        "year": 2006,
        "doi": "10.1001/archinte.166.10.1092",
        "pmid": "16717171",
        "url": "https://pubmed.ncbi.nlm.nih.gov/16717171/",
        "supports": "GAD-7 支持广泛性焦虑筛查与严重度评估。",
        "caveat": "GAD-7 不能替代结构化临床诊断。",
    },
    "panss_1987": {
        "id": "panss_1987",
        "module": "reference_range",
        "method": "PANSS_total",
        "title": "The Positive and Negative Syndrome Scale (PANSS) for schizophrenia",
        "authors": "Kay SR, Fiszbein A, Opler LA",
        "venue": "Schizophrenia Bulletin",
        "year": 1987,
        "doi": "10.1093/schbul/13.2.261",
        "pmid": "3616518",
        "url": "https://pubmed.ncbi.nlm.nih.gov/3616518/",
        "supports": "PANSS 支持精神分裂症阳性、阴性和一般精神病理症状量化。",
        "caveat": "PANSS 评分需由受训评估者完成，并结合病程和功能信息解释。",
    },
    "psqi_1989": {
        "id": "psqi_1989",
        "module": "reference_range",
        "method": "PSQI_total",
        "title": "The Pittsburgh Sleep Quality Index: a new instrument for psychiatric practice and research",
        "authors": "Buysse DJ, Reynolds CF, Monk TH, Berman SR, Kupfer DJ",
        "venue": "Psychiatry Research",
        "year": 1989,
        "doi": "10.1016/0165-1781(89)90047-4",
        "pmid": "2748771",
        "url": "https://pubmed.ncbi.nlm.nih.gov/2748771/",
        "supports": "PSQI 支持过去 1 个月主观睡眠质量和睡眠障碍评估。",
        "caveat": "PSQI 是自评睡眠质量工具，不能单独区分所有睡眠障碍病因。",
    },
    "isi_2011": {
        "id": "isi_2011",
        "module": "reference_range",
        "method": "ISI_total",
        "title": "The Insomnia Severity Index: psychometric indicators to detect insomnia cases and evaluate treatment response",
        "authors": "Morin CM, Belleville G, Belanger L, Ivers H",
        "venue": "Sleep",
        "year": 2011,
        "doi": "10.1093/sleep/34.5.601",
        "pmid": "21532953",
        "url": "https://pubmed.ncbi.nlm.nih.gov/21532953/",
        "supports": "ISI 支持失眠严重度筛查和治疗反应监测。",
        "caveat": "ISI 反映主观失眠严重度，复杂睡眠障碍需进一步评估。",
    },
    "zimmerman_2013": {
        "id": "zimmerman_2013",
        "module": "reference_range",
        "method": "HAMD_total_severity_cutoff",
        "title": "Severity classification on the Hamilton Depression Rating Scale",
        "authors": "Zimmerman M, Martinez JH, Young D, Chelminski I, Dalrymple K",
        "venue": "Journal of Affective Disorders",
        "year": 2013,
        "doi": "10.1016/j.jad.2012.11.026",
        "pmid": "23759278",
        "url": "https://pubmed.ncbi.nlm.nih.gov/23759278/",
        "supports": "基于 627 例门诊患者 ROC 分析得出 HAMD-17 严重度分级：无 0-7，轻度 8-16，中度 17-23，重度 ≥24。",
        "caveat": "该分级基于成人门诊 MDD 患者样本；用于其他人群（如青少年）需谨慎外推。",
    },
    "matza_2010": {
        "id": "matza_2010",
        "module": "reference_range",
        "method": "HAMA_total_severity_cutoff",
        "title": "Identifying HAM-A cutoffs for mild, moderate, and severe generalized anxiety disorder",
        "authors": "Matza LS, Morlock R, Sexton C, Malley K, Feltner D",
        "venue": "International Journal of Methods in Psychiatric Research",
        "year": 2010,
        "doi": "10.1002/mpr.323",
        "pmid": "20641148",
        "url": "https://doi.org/10.1002/mpr.323",
        "supports": "基于 GAD 随机对照试验数据与 CGI-S 一致性分析得出 HAM-A 严重度分级：无/轻微 0-7，轻度 8-14，中度 15-23，重度 ≥24。",
        "caveat": "该分级来自 GAD 治疗试验样本（n=144），提出者建议在更大样本中进一步验证。",
    },
    "leucht_2005_panss": {
        "id": "leucht_2005_panss",
        "module": "reference_range",
        "method": "PANSS_total_severity_anchor",
        "title": "What does the PANSS mean?",
        "authors": "Leucht S, Kane JM, Kissling W, Hamann J, Etschel E, Engel RR",
        "venue": "Schizophrenia Research",
        "year": 2005,
        "doi": "10.1016/j.schres.2005.07.014",
        "pmid": "16198088",
        "url": "https://pubmed.ncbi.nlm.nih.gov/16198088/",
        "supports": "基于 4091 例急性加重期精神分裂症患者的等百分位链接分析，PANSS 总分约 58/75/95/116 分别对应 CGI 轻度/中度/明显/重度病情。",
        "caveat": "该锚定值来自急性加重期抗精神病药试验人群，不应机械套用于稳定期或其他亚组；治疗反应更推荐用相对基线变化率（如 ≥50% 降低）定义。",
    },
    "leucht_2005_bprs": {
        "id": "leucht_2005_bprs",
        "module": "reference_range",
        "method": "BPRS_total_severity_anchor",
        "title": "Clinical implications of Brief Psychiatric Rating Scale scores",
        "authors": "Leucht S, Kane JM, Etschel E, Kissling W, Hamann J, Engel RR",
        "venue": "Neuropsychopharmacology",
        "year": 2005,
        "doi": "10.1038/sj.npp.1300850",
        "pmid": "16123764",
        "url": "https://pubmed.ncbi.nlm.nih.gov/16123764/",
        "supports": "基于 CGI 等百分位链接，18 项 BPRS（1-7 计分，范围 18-126）约 31/41/53 分别对应 CGI 轻度/中度/重度病情。",
        "caveat": "锚定值来自急性加重期人群，个体化解释需结合临床访谈。",
    },
    "richardson_2010_adolescent_phq9": {
        "id": "richardson_2010_adolescent_phq9",
        "module": "reference_range",
        "method": "PHQ9_total_adolescent_cutoff",
        "title": "Evaluation of the Patient Health Questionnaire-9 Item for detecting major depression among adolescents",
        "authors": "Richardson LP, McCauley E, Grossman DC, McCarty CA, Richards J, Russo JE, Rockhill C, Katon W",
        "venue": "Pediatrics",
        "year": 2010,
        "doi": "10.1542/peds.2010-0852",
        "pmid": "21041282",
        "url": "https://pubmed.ncbi.nlm.nih.gov/21041282/",
        "supports": "442 例 13-17 岁青少年对 DISC-IV 结构化访谈验证：PHQ-9 ≥11 分检出青少年重度抑郁的敏感度 89.5%、特异度 77.5%（AUC 0.88）。",
        "caveat": "该研究给出的是筛查阳性切点（≥11），不是严重度分级；青少年 HAMD-17 缺乏专属验证分级，本系统沿用成人量表分级并降低阈值以提高敏感性，正式诊断应参照 CDRS-R（Poznanski & Mokros 1995）等儿童专用工具。",
    },
    "welch_1947": {
        "id": "welch_1947",
        "module": "reference_range",
        "method": "Welch t-test",
        "title": "The generalisation of Student's problems when several different population variances are involved",
        "authors": "Welch BL",
        "venue": "Biometrika",
        "year": 1947,
        "doi": "10.1093/biomet/34.1-2.28",
        "pmid": "20287819",
        "url": "https://pubmed.ncbi.nlm.nih.gov/20287819/",
        "supports": "Welch t 检验用于两组均值比较，允许方差不齐。",
        "caveat": "小样本、非正态或强偏态数据应考虑非参数或重抽样方法。",
    },
    "followup_phq9_2004": {
        "id": "followup_phq9_2004",
        "module": "followup",
        "method": "longitudinal_scale_tracking",
        "title": "Sensitivity to change of the Patient Health Questionnaire-9",
        "authors": "Lowe B, Unutzer J, Callahan CM, Perkins AJ, Kroenke K",
        "venue": "Journal of Affective Disorders",
        "year": 2004,
        "doi": "10.1016/S0165-0327(03)00198-8",
        "pmid": "15183601",
        "url": "https://pubmed.ncbi.nlm.nih.gov/15183601/",
        "supports": "PHQ-9 等量表可用于随访中监测症状变化和治疗结局。",
        "caveat": "趋势图展示变化，不自动证明治疗因果效应。",
    },
    "tripod_2015": {
        "id": "tripod_2015",
        "module": "risk_prediction",
        "method": "prediction_model_reporting",
        "title": "Transparent reporting of a multivariable prediction model for individual prognosis or diagnosis (TRIPOD)",
        "authors": "Collins GS, Reitsma JB, Altman DG, Moons KGM",
        "venue": "Annals of Internal Medicine",
        "year": 2015,
        "doi": "10.7326/M14-0697",
        "pmid": "25560714",
        "url": "https://www.acpjournals.org/doi/10.7326/M14-0697",
        "supports": "临床预测模型开发、验证和报告需透明披露数据、预测因子、结局、性能和限制。",
        "caveat": "未完成外部验证和校准评估的模型只能作为研究/辅助分析，不可直接用于临床处置。",
    },
    "probast_2019": {
        "id": "probast_2019",
        "module": "risk_prediction",
        "method": "risk_of_bias",
        "title": "PROBAST: A Tool to Assess the Risk of Bias and Applicability of Prediction Model Studies",
        "authors": "Wolff RF et al.",
        "venue": "Annals of Internal Medicine",
        "year": 2019,
        "doi": "10.7326/M18-1376",
        "pmid": "30596875",
        "url": "https://pubmed.ncbi.nlm.nih.gov/30596875/",
        "supports": "预测模型需要从参与者、预测因子、结局和分析四个域评估偏倚和适用性。",
        "caveat": "本系统返回的 AUC/F1 等指标不等于完成 PROBAST 低偏倚认证。",
    },
    "nice_self_harm_2022": {
        "id": "nice_self_harm_2022",
        "module": "risk_prediction",
        "method": "self_harm_safety_caveat",
        "title": "Self-harm: assessment, management and preventing recurrence (NICE NG225)",
        "authors": "National Institute for Health and Care Excellence",
        "venue": "NICE guideline",
        "year": 2022,
        "doi": None,
        "pmid": None,
        "url": "https://www.nice.org.uk/guidance/ng225/chapter/Recommendations",
        "supports": "自伤评估应聚焦个体需求、安全和心理社会评估。",
        "caveat": "不得用风险工具或低/中/高分层单独预测自杀/自伤或决定治疗、出院、转诊。",
    },
    "breiman_2001": {
        "id": "breiman_2001",
        "module": "risk_prediction",
        "method": "RandomForest",
        "title": "Random Forests",
        "authors": "Breiman L",
        "venue": "Machine Learning",
        "year": 2001,
        "doi": "10.1023/A:1010933404324",
        "pmid": None,
        "url": "https://link.springer.com/article/10.1023/A:1010933404324",
        "supports": "随机森林是基于多棵随机化决策树的集成分类/回归方法。",
        "caveat": "特征重要性是模型内部统计量，不能直接解释为临床因果贡献。",
    },
    "cox_1958": {
        "id": "cox_1958",
        "module": "risk_prediction",
        "method": "LogisticRegression",
        "title": "The regression analysis of binary sequences",
        "authors": "Cox DR",
        "venue": "Journal of the Royal Statistical Society Series B",
        "year": 1958,
        "doi": "10.1111/j.2517-6161.1958.tb00292.x",
        "pmid": None,
        "url": "https://rss.onlinelibrary.wiley.com/doi/abs/10.1111/j.2517-6161.1958.tb00292.x",
        "supports": "Logistic 回归适用于二分类结局概率建模。",
        "caveat": "系数解释依赖变量编码、建模假设和混杂控制。",
    },
    "hanley_mcneil_1982": {
        "id": "hanley_mcneil_1982",
        "module": "risk_prediction",
        "method": "ROC_AUC",
        "title": "The meaning and use of the area under a receiver operating characteristic (ROC) curve",
        "authors": "Hanley JA, McNeil BJ",
        "venue": "Radiology",
        "year": 1982,
        "doi": "10.1148/radiology.143.1.7063747",
        "pmid": "7063747",
        "url": "https://pubmed.ncbi.nlm.nih.gov/7063747/",
        "supports": "ROC/AUC 可量化分类模型区分能力。",
        "caveat": "AUC 不评估校准、临床净获益或阈值处置安全性。",
    },
    "borsboom_cramer_2013": {
        "id": "borsboom_cramer_2013",
        "module": "comorbidity",
        "method": "psychopathology_network",
        "title": "Network Analysis: An Integrative Approach to the Structure of Psychopathology",
        "authors": "Borsboom D, Cramer AOJ",
        "venue": "Annual Review of Clinical Psychology",
        "year": 2013,
        "doi": "10.1146/annurev-clinpsy-050212-185608",
        "pmid": "23537483",
        "url": "https://pubmed.ncbi.nlm.nih.gov/23537483/",
        "supports": "精神病理网络可用于展示症状/诊断之间的关联结构。",
        "caveat": "横断面网络边表示统计关联或共现，不等同于症状间因果路径。",
    },
    "mood_anxiety_comorbidity_2020": {
        "id": "mood_anxiety_comorbidity_2020",
        "module": "comorbidity",
        "method": "depression_anxiety_comorbidity",
        "title": "Co-morbidity between mood and anxiety disorders: A systematic review and meta-analysis",
        "authors": "Saha S et al.",
        "venue": "Depression and Anxiety",
        "year": 2021,
        "doi": "10.1002/da.23113",
        "pmid": "33225514",
        "url": "https://pubmed.ncbi.nlm.nih.gov/33225514/",
        "supports": "心境障碍与焦虑障碍存在稳定共病证据。",
        "caveat": "本系统基于诊断字段和量表阈值提示共病信号，不生成正式共病诊断。",
    },
    "sleep_anxiety_depression_2013": {
        "id": "sleep_anxiety_depression_2013",
        "module": "comorbidity",
        "method": "sleep_symptom_association",
        "title": "A systematic review assessing bidirectionality between sleep disturbances, anxiety, and depression",
        "authors": "Alvaro PK, Roberts RM, Harris JK",
        "venue": "Sleep",
        "year": 2013,
        "doi": "10.5665/sleep.2810",
        "pmid": "23814343",
        "url": "https://pubmed.ncbi.nlm.nih.gov/23814343/",
        "supports": "睡眠问题与焦虑、抑郁存在双向关联证据。",
        "caveat": "睡眠-症状关联需区分时间顺序、药物影响和躯体共病。",
    },
    "benjamini_hochberg_1995": {
        "id": "benjamini_hochberg_1995",
        "module": "correlation",
        "method": "multiple_comparison_correction",
        "title": "Controlling the False Discovery Rate: A Practical and Powerful Approach to Multiple Testing",
        "authors": "Benjamini Y, Hochberg Y",
        "venue": "Journal of the Royal Statistical Society Series B",
        "year": 1995,
        "doi": "10.1111/j.2517-6161.1995.tb02031.x",
        "pmid": None,
        "url": "https://doi.org/10.1111/j.2517-6161.1995.tb02031.x",
        "supports": "对同一数据集中的多重相关性检验，应使用 FDR（如 Benjamini-Hochberg）或 Bonferroni 校正控制假阳性率。",
        "caveat": "未校正的多重比较会显著抬高假阳性率；相关矩阵中的显著性判定应报告校正后 q 值。",
    },
    "pearson_1895": {
        "id": "pearson_1895",
        "module": "correlation",
        "method": "pearson",
        "title": "Notes on regression and inheritance in the case of two parents",
        "authors": "Pearson K",
        "venue": "Proceedings of the Royal Society of London",
        "year": 1895,
        "doi": "10.1098/rspl.1895.0041",
        "pmid": None,
        "url": "https://doi.org/10.1098/rspl.1895.0041",
        "supports": "Pearson 相关用于连续变量线性关联度量。",
        "caveat": "Pearson 相关对离群值和非线性关系敏感，相关不代表因果。",
    },
    "spearman_1904": {
        "id": "spearman_1904",
        "module": "correlation",
        "method": "spearman",
        "title": "The proof and measurement of association between two things",
        "authors": "Spearman C",
        "venue": "American Journal of Psychology",
        "year": 1904,
        "doi": "10.2307/1412159",
        "pmid": None,
        "url": "https://doi.org/10.2307/1412159",
        "supports": "Spearman 秩相关用于单调关联和非正态数据的秩次分析。",
        "caveat": "秩相关仍是关联分析，不能证明方向性或因果。",
    },
    "kendall_1938": {
        "id": "kendall_1938",
        "module": "correlation",
        "method": "kendall",
        "title": "A new measure of rank correlation",
        "authors": "Kendall MG",
        "venue": "Biometrika",
        "year": 1938,
        "doi": "10.1093/biomet/30.1-2.81",
        "pmid": None,
        "url": "https://academic.oup.com/biomet/article/30/1-2/81/176907",
        "supports": "Kendall tau 用于秩一致性和序数关联分析。",
        "caveat": "样本小或重复值多时需谨慎解释显著性。",
    },
}

MODULE_DEFAULT_EVIDENCE = {
    "patient_query": ["strobe_2007", "record_2015", "ohdsi_cohort_2021"],
    "reference_range": ["hamd_1960", "zimmerman_2013", "hama_1959", "matza_2010", "phq9_2001", "richardson_2010_adolescent_phq9", "gad7_2006", "panss_1987", "leucht_2005_panss", "leucht_2005_bprs", "psqi_1989", "isi_2011"],
    "followup": ["followup_phq9_2004", "hamd_1960", "phq9_2001", "welch_1947"],
    "risk_prediction": ["tripod_2015", "probast_2019", "nice_self_harm_2022", "breiman_2001", "cox_1958", "hanley_mcneil_1982"],
    "comorbidity": ["borsboom_cramer_2013", "mood_anxiety_comorbidity_2020", "sleep_anxiety_depression_2013", "zimmerman_2013", "matza_2010", "phq9_2001", "psqi_1989"],
    "report": ["strobe_2007", "record_2015", "tripod_2015", "probast_2019"],
    "correlation": ["pearson_1895", "spearman_1904", "kendall_1938", "benjamini_hochberg_1995"],
}


def get_evidence(ids: Optional[Iterable[str]] = None, module: Optional[str] = None, method: Optional[str] = None) -> List[dict]:
    """Return verified evidence entries, optionally filtered by ids/module/method."""
    if ids is not None:
        entries = [EVIDENCE_REGISTRY[eid] for eid in ids if eid in EVIDENCE_REGISTRY]
    else:
        entries = list(EVIDENCE_REGISTRY.values())
    if module:
        entries = [e for e in entries if e.get("module") == module]
    if method:
        method_l = method.lower()
        entries = [e for e in entries if method_l in str(e.get("method", "")).lower()]
    return [dict(e) for e in entries]


def module_evidence(module: str, extra_ids: Optional[Iterable[str]] = None) -> List[dict]:
    ids = list(MODULE_DEFAULT_EVIDENCE.get(module, []))
    if extra_ids:
        ids.extend([eid for eid in extra_ids if eid not in ids])
    return get_evidence(ids)


def methodology(module: str, extra_ids: Optional[Iterable[str]] = None, caveat: str = "") -> dict:
    evidence = module_evidence(module, extra_ids)
    caveats = [e["caveat"] for e in evidence if e.get("caveat")]
    if caveat:
        caveats.insert(0, caveat)
    return {
        "module": module,
        "evidence": evidence,
        "clinical_caveats": caveats,
    }
